baseurl = "http://infosofbentog.github.io"
languageCode = "fr-fr"
title = "Automne en Afrique"
theme = "hyde"
[indexes]
   Catégorie = "Catégories"
[params]
  Description= "à la recherche du haricot magique"